apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ai-safeguard
  namespace: ai-safeguard
spec:
  ingressClassName: nginx
  rules:
    - host: ai-safeguard.dev.theblockbrain.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ai-safeguard
                port:
                  number: 80
