apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: ai-safeguard-secrets
  namespace: ai-safeguard
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: parameterstore
    kind: ClusterSecretStore
  data:
    - secretKey: firebase-config
      remoteRef:
        key: dev.ai-safeguard.firebase-config
        property: config